version: '3.3'
services:
  db:
    image: 'postgres:12'
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  backend:
    image: ${IMAGE_TAG_BACKEND}
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${STAGING_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=web"

