version: '3.3'
services:
  db:
    image: 'postgres:12'
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

    ports:
      - '5432:5432'

  backend:
    image: 'node:12'
    working_dir: '/var/app/backend'
    command: 'npm run start'
    volumes:
      - './:/var/app/backend'
    ports:
      - '3000:3000'
